# Site settings
title: UDAY KUMAR
twitter_username: TiM3ParaD0x
name: Uday Kumar

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://udayom.blogspot.com/
 - title: GitHub
   url: https://github.com/udayom/
 - title: Facebook
   url: http://facebook.com/udayom/
 - title: LinkedIn
   url: https://www.linkedin.com/in/udayom/

#Any buzzword skills you want to include
skills:
 - Cyber Security
 - Risk Assessment
 - Risk Management
 - Automation
 - Information Security
 - DevSecOps
 - Digital Forensics
 - Cyber Forensics
 - VAPT
 - Compliance
 - Security Awareness
 - Agile Methodology
 - Training
 - GRC

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://udayom.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Cyber Security Risk Analyst - GRC
   start: 2019
   end: Ongoing
   employer: Emirates Group
   description: Ensure a comprehensive IT Risk Management framework is established to identify, analyze, mitigate, monitor and communicate IT risks across Emirates IT. Collect IT risks identified through various channels eg. risk assessments, incidents, log them in the IT Risk Register and perform continuous monitoring activities. Perform regular risk assessments on Third Party, Cybersecurity, Project and Program and IT operations risks. Perform risk assessment reports and present the results to Management. Produce regular risk reports for all IT departments, and Top risks report for Senior Management. Develop Key Risk Indicators (KRIs) for IT and create dashboards for continuous monitoring of the risks. Periodically assess, improve and develop Cybersecurity controls, policies, processes and standards. Conduct regular IT and Cybersecurity maturity assessments, bench-marking assignments and gap assessments against industry best practices to identify areas of improvement. Design, develop and maintain a Cybersecurity scorecard by business area, to assess the Cybersecurity posture - Identify key metrics covering all Cybersecurity areas, automate the data collection and scorecard production for all business areas, present the scorecard to the business. Monitor and track IT regulatory requirements. Keep abreast of emerging risks and industry standards, and assess the potential impact on the organization. Produce regular reporting to Senior Management. Support contribute to the IT security awareness campaign by organizing roadshows, publishing articles, or conducting on-site Cybersecurity training. Conduct awareness training and workshops on IT Risk Management. Manage daily security exceptions requests- Assess, review and action requests for exceptions to policies and standards from all levels of the organization, both corporate and IT users. Maintain an up-to-date repository of all the exceptions granted and communicate the exceptions to relevant business-technical units.
 - title: Cyber Security Lead
   start: 2018
   end: 2019
   employer: Khidmaty Government Services
   description: Operational and Governance related tasks that relates to Security for Client ASGC, Dubai. Major task includes the Defining and Implementation of Information Security Policies and Procedures as per ISO27001 Standards. The Automation of Management Reports, Analyze the vulnerabilities found in infrastructure by Vulnerability Analysis and Penetration Testing (Manual+Automated), Threat Remediation, highlight risk to management, risk assessment, vendor management, security checks for vendor, hardening checks on the Oracle Linux operating system, schedule Antivirus scans and highlight the Major vulnerability to IT Infra team, schedule patch management, Ensure compliance of the policies on the servers, Manage and Administer IT security and Forensic tools such as LanSweeper, QualysGuard, Symantec Endpoint protection, ATP, ETP, EDR, MS Office 365 Admin, Azure Portal Admin, Cloud Server Management Activities like New Provisioning server, Migrate, Destroy server etc. Perform VAPT on in-house Applications using OpenVAS. SIEM configuration (AlienVault), Cyber Operations, Reporting, Demonstration. Investigation of the attacks, Fortinet Firewall Rules review (nipper), log and memory based analysis, Forensic evidence finding (SIEM Log and Dump based) Technical Policy defining and Implementation in Symantec Endpoint Protection, Data Leakage Protection (DLP), Email+Cloud Security, Email Threat Protection (FireEye, Microsoft, Mimecast), Web Isolation modules. Check More on <a href="https://www.linkedin.com/in/udayom" taget="_blank">LinkedIn Profile</a>
 - title: CISO - IT Security Manager
   start: 2017
   end: 2018
   employer: Finacus Solutions
   description: Automation with Security Compliance checks, Policy procedures defining, ISO/IEC 27001, PCI-DSS implementation, Process Management, Incident Management, Change management, Automation of operational tasks, Internal Security Auditing, VAPT, Continuous Development and Automation with open-source tools (DevOps), Complete Financial Domain, Payment gateway interface Audit as per PCI DSS Compliance, Process Auditing. Reporting ROC (Report on Compliance), ROV (Report on Validation), Performing ASV Scans as part of PCI DSS Implementation. Major Responsibility included all the Operational and Governance related tasks that relates to Security for Finacus Solutions Pvt. Ltd. which deals with its various clients (100+) as Reputed Banks spread across India. Major task included the Defining and Implementation of Information Security Policies and Procedures. The Automation of business requirements and management, covered Change management, Incident Management, Asset Inventory, Helpdesk, Ticketing, Effort Tracking and Documentation storage Automation. Administering Azure account for system integration of ticketing system. From DevSecOps section, have covered configuration, implementation and Maintenance of various monitoring tool such as Nagios, Baretail, OpenNMS, Graylog, RanCID. Automated Email/SMS Triggering from monitoring tool if critical alert arrives as per business requirement. Configuring and Administration of Manage Engine PIM Tool Password Manager Pro, WatchGuard Firewall Rules, Implementing Trend Micro Anti-Virus, Involvement of banking domain requires more emphasize on PCI-DSS compliance which talks about internal and external Auditing reports. Jenkins Automation for day to day jobs as well as code deployment on Linux servers via Shell Scripts developed and implemented. Following Agile Way of Methodology with Sprint Framework and DevSecOps Practice to achieve Automation with End to End Project workflow Integration including Automated Security Check Components.
 - title: Cyber Security Analyst
   start: 2014
   end: 2017
   employer: Capgemini
   description:  Governance Security - Manage Audits, Compliance check along with certifications for various standards such as ISO 27001- 2013 and PCI DSS. Multi-operational experience in Networking Operations, Systems Administration, Security and Audit and Support of Heterogeneous IT Infrastructure and BCP/DR. Handling Incident Management.Formulating, Reviewing, Upgrading, Developing Policy, Procedures and Guidelines for elements governing/connected to ISO Standards, Analyze SIEM tools, IDS and auctioning on alerts Operational Security- Involved in Vulnerability Analysis and Penetration Testing, worked on tools like burpsuite, IBM Appscanner, OWASP top 10, wapiti, Paros proxy, Nikto, Nessus, metasploite etc.IPS and DDOS mitigation device reports analysis firewall rule dump and analysis, proxy logs, user administration, OSSEC, SIEM tool monitoring and configuration, ITIL Tool - Service now.Cyber Forensics and Analysis using tools like The Sleuth Kit, Autopsy, Rekall, DumpIT, Volatility, log2timeline and most of the tools from Kali Linux OS. Handled SOC activities in which Analysis of complete trail of activities of user based on the logs and extracting footprints for legal purpose to be dealt with Cyber Law team. DevSecOps- Digital Transformation of Project-  Worked on Multiple open source tools like Nagios, Munin, graphite, Jenkins, Apache,  ldap, mongodb, maven, Exim, ELK stack, graylog, graphite, redis-cache, memcache, exim, Linux shell scripting, Automation with Jenkins, Ansible, PuppetTo design business rule-based dashboards in AppDynamic. To make dashboards and alerts in AppDynamics based on Business requirement. AppDynamics deployment and complete setup Project Management- Experience on Atlassian tools like JIRA, Confluence, stash, bitbucket. Studied ITIL Fv4 and worked on Kanban boards for project progress tracking. Project management experience for deployment, schedule.Good at Incident, Change management, onshore and offshore interaction Documentation. Check More on <a href="https://www.linkedin.com/in/udayom" taget="_blank">LinkedIn Profile</a>
 - title: SOC Intern Engineer
   start: 2013
   end: 2014
   employer: Asian Associates
   description: Performed Vulnerability Analysis and Penetration Testing, worked on Linux based open source tools like burpsuite, OWASP, Nikto, wapiti, Paros proxy, Nessus, metasploite etc. Implemented and Administered IPS and Performed DDOS mitigation device reports analysis, Forensic Analysis on attack trace, proxy logs, user administration. Complete SOC level Monitoring setup including Nagios, OSSEC, SIEM tool monitoring and configuration. Tweaking in existing scripts/IT Tools for performance boosting and Automating of the tasks performed. Check More on <a href="https://www.linkedin.com/in/udayom" taget="_blank">LinkedIn Profile</a>

#Education is required
education:
 - level: Master of Engineering (M.Engg)
   date: 2014
   subject: Information Technology
   school: University of Mumbai
 - level: Bachelor of Engineering (B.Engg)
   date: 2012
   subject: Electronics and Telecommunications
   school: University of Mumbai

#This section is optional (as is the image link below)
certifications:
   profileurl: https://www.linkedin.com/in/udayom
   course:
    - title: OneTrust GRC Professional
      link: https://raw.githubusercontent.com/udayom/udayom.github.io/master/cert/grc-prof.png
      optionalimage: https://raw.githubusercontent.com/udayom/udayom.github.io/master/img/OneTrust.png
      date: Oct 30, 2021
    - title: Certified in Risk and Information Systems Control (CRISC)
      link: https://raw.githubusercontent.com/udayom/udayom.github.io/master/cert/crisc-cert.png
      optionalimage: https://raw.githubusercontent.com/udayom/udayom.github.io/master/img/crisc.png
      date: Nov 5, 2020
    - title: Computer Hacking Forensic Investigator (CHFI)
      link: https://aspen.eccouncil.org/VerifyBadge?type=certification&a=z9HKV3jBjCb0hl0gco/MszNSWxJmNxshyeI2sw5kWtU=
      optionalimage: https://raw.githubusercontent.com/udayom/udayom.github.io/master/img/CHFI.jpg
      date: May 22, 2020
    - title: Certified Information System Security Professional (CISSP)
      link: https://raw.githubusercontent.com/udayom/udayom.github.io/master/cert/cissp-isc2.png
      optionalimage: https://raw.githubusercontent.com/udayom/udayom.github.io/master/img/cissp.png
      date: May 19, 2020
    - title: ISO 31000 Risk Management Professional
      link: https://raw.githubusercontent.com/udayom/udayom.github.io/master/cert/iso31k.png
      optionalimage: https://raw.githubusercontent.com/udayom/udayom.github.io/master/img/ISO31k.png
      date: April 30, 2020
    - title: EU GDPR Practioner (GDPR)
      link: https://raw.githubusercontent.com/udayom/udayom.github.io/master/cert/gdpr-practitioner.png
      optionalimage: https://raw.githubusercontent.com/udayom/udayom.github.io/master/img/EU-GDPR.png
      date: April 28, 2020
    - title: Certified Chief Information Security Officer (C|CISO)
      link: https://aspen.eccouncil.org/VerifyBadge?type=certification&a=IpQpK9fbi3TDnn80XmMdm8iIpCG22cXKW2lOSxc8DXc=
      optionalimage: https://raw.githubusercontent.com/udayom/udayom.github.io/master/img/CCISO.png
      date: April 10, 2019
    - title: AWS Certified Solution Architect - Associate
      link: https://www.certmetrics.com/amazon/public/badge.aspx?i=1&t=c&d=2019-03-02&ci=AWS00805287&dm=80
      optionalimage: https://raw.githubusercontent.com/udayom/udayom.github.io/master/img/AWS.png
      date: March 02, 2019
    - title: Certified Ethical Hacking
      link: https://aspen.eccouncil.org/VerifyBadge?type=certification&a=nYMsFOnMM38LHrQrms6ZXOcuVd4L8B1hgmf9vkA9vcg=
      optionalimage: https://raw.githubusercontent.com/udayom/udayom.github.io/master/img/CEH.png
      date: February 4, 2019
    - title: Diploma in Cyber Law
      link: https://raw.githubusercontent.com/udayom/udayom.github.io/master/cert/dcl-cert.jpg
      optionalimage: https://raw.githubusercontent.com/udayom/udayom.github.io/master/img/Cyberlaw.png
      date: January 28, 2018
    - title: Agile Methodology & Project Management
      link: https://www.udemy.com/certificate/UC-COYMV2YG/
      optionalimage: https://raw.githubusercontent.com/udayom/udayom.github.io/master/img/agile.png
      date: January 28, 2018
    - title: PCI-DSS Implementation
      link: https://raw.githubusercontent.com/udayom/udayom.github.io/master/cert/pcidss-cert.jpg
      optionalimage: https://raw.githubusercontent.com/udayom/udayom.github.io/master/img/pci-dss.png
      date: September 23, 2017
    - title: ISO 27001 Lead Auditor
      link: https://raw.githubusercontent.com/udayom/udayom.github.io/master/cert/iso27k1-cert.JPG
      optionalimage: https://raw.githubusercontent.com/udayom/udayom.github.io/master/img/ISO27k.png
      date: February 4, 2017


#List of interesting Github repo/projects to include - optional
github:
 - udayom/udayom.github.io
 - udayom/OSCP-Study-Notes
 - udayom/Capistrano-Deploy
 - udayom/glpi
 - udayom/PyPractice

#Stackoverflow flair is optional
hackthebox:
   profileurl: https://www.hackthebox.eu/home/users/profile/74322
   flairimageurl: https://raw.githubusercontent.com/udayom/udayom.github.io/master/img/htb.ico

about:
   profileurl: https://www.linkedin.com/in/udayom/

intro: |
   With 7+ years of Experience, I have <b>significant experience working across a range</b> of Cyber Security activities, including strong background of <b>Risk assessment</b> for projects, third party, applications to compliance for the organisation. I have good grasp on the frameworks such as <b>ISO 27001, PCI-DSS</b> and had multiple opportunities to get organisation certified by handling end to end activities involved in process.</br></br>
   I also enjoy working on shell scripts for Automation and Forensically Investigating the Cyber Security Incidents to uncover the real <b>intent</b> of an attack/Hack. I like the Automation approach wherever it is possible to implement and promote the DevSecOps culture whenever I get opportunity on. </br></br> <b>Dedicating my</b> efforts towards literature to understand the <b>root cause of Cyber Security events and Hackers perspective/behaviour</b> is a passion of mine.  <b>I also hold myself to a high standard when it comes to listening to a problem statement and working to deliver the right solution/practice for my clients</b>.</br></br> 
   I have worked on my <a href="https://www.github.com/udayom" target="_blank">GitHub Profile</a> to provide an overview of my <b>career history and expertise</b> here. You can also find more information here on my <a href="https://www.linkedin.com/in/udayom/" taget="_blank">LinkedIn Profile</a>

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   Technical Youtube Tutorials and blog posts that can be checked (pardon my spooky voice-over) üßëüèª‚Äçüíª - </br></br> 
   <iframe width="560" height="315" src="https://www.youtube.com/embed/9T30_rCWnww" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> </br></br>
   <a href="https://youtube.com/playlist?list=PLh_cLpwIeGjeyBXBTi81FzMVVjOXSGdq9" taget="_blank">My Favourite Songs Playlist (English) üéµ</a> </br></br>
   </br>
   <a href="https://www.youtube.com/playlist?list=PLh_cLpwIeGjcIwc82DHZxGki0o4vkx5xl" taget="_blank">Kinda favourites Hindi songs - not updated) üéµ</a> </br></br>
   <a href="https://www.facebook.com/udayom" taget="_blank">My Facebook profile </a>  </br>
   <a href="https://www.instagram.com/uday0m" taget="_blank">My Instagram profile </a>  </br>
   <a href="https://twitter.com/TiM3ParaD0x" taget="_blank">My Twitter page </a>  </br>
   <a href="https://www.credly.com/users/udayom/badges" taget="_blank">My Acclaim Credly Badges page </a>  </br>
   

#A Smarkskill section to add something extra - added personally by OM out of intrest and learning - can be text or HTML
smartskill: |
   Uday, Nicknamed as U-DAY, (sometimes OM), also takes immense interest in going creative. He has great leaning towards Yogaüßò‚Äç‚ôÇÔ∏è, swimmingüèäüèª‚Äç‚ôÇÔ∏è and meditationüôáüèª. Moreover, few ü§Ø mind-yoga tricks shown are unique content by him on youtube. Here are some Interesting (and Innovative If I may say so üòâ) exercises that help balance left-right brain co-ordination. Have a look at the playlist, give it a quick try if you will! They're short 20 seconds videos ‚è≥üïî </br></br>
   <iframe width="560" height="315" src="https://www.youtube.com/embed/videoseries?list=PLh_cLpwIeGjcR9KYKIfwa6GEcm1GAiz5P" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

